/**
 * Hooks para `proposal_interactions`.
 *
 * Cobertura:
 *  - useProposalInteractions(proposalId, filters?) — lista cronológica decrescente.
 *  - useCreateProposalInteraction() — registro manual.
 *  - useRecordAutoInteraction() — atalho pra auto-registro (botão WhatsApp etc.).
 *  - useUpdateProposalInteraction() / useDeleteProposalInteraction() (soft delete).
 *
 * Tudo invalida cache via helper centralizado de cacheInvalidation.
 */
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";
import type {
  ProposalInteraction,
  ProposalInteractionChannel,
  ProposalInteractionDirection,
} from "@/types/proposalInteractions";

export interface InteractionFilters {
  channel?: ProposalInteractionChannel | "todos";
  direction?: ProposalInteractionDirection | "todos";
  /** ISO date (yyyy-mm-dd) — limites inclusivos. */
  from?: string | null;
  to?: string | null;
}

export function useProposalInteractions(
  proposalId: string | undefined,
  filters: InteractionFilters = {},
) {
  return useQuery({
    queryKey: ["proposal_interactions", proposalId, filters],
    enabled: !!proposalId,
    queryFn: async (): Promise<ProposalInteraction[]> => {
      let q = supabase
        .from("proposal_interactions" as any)
        .select("*")
        .eq("proposal_id", proposalId!)
        .is("deleted_at", null)
        .order("interaction_at", { ascending: false })
        .limit(500);

      if (filters.channel && filters.channel !== "todos") q = q.eq("channel", filters.channel);
      if (filters.direction && filters.direction !== "todos") q = q.eq("direction", filters.direction);
      if (filters.from) q = q.gte("interaction_at", `${filters.from}T00:00:00Z`);
      if (filters.to) q = q.lte("interaction_at", `${filters.to}T23:59:59Z`);

      const { data, error } = await q;
      if (error) throw error;
      return (data || []) as unknown as ProposalInteraction[];
    },
  });
}

export interface CreateInteractionPayload {
  proposalId: string;
  channel: ProposalInteractionChannel;
  direction: ProposalInteractionDirection;
  interactionAt: string; // ISO completo
  summary: string;
  details?: string | null;
  autoGenerated?: boolean;
  metadata?: Record<string, unknown>;
}

async function insertInteraction(payload: CreateInteractionPayload) {
  const userRes = await supabase.auth.getUser();
  const uid = userRes.data.user?.id ?? null;

  const summary = payload.summary.trim().slice(0, 200);
  if (!summary) throw new Error("Resumo é obrigatório");

  const { data, error } = await supabase
    .from("proposal_interactions" as any)
    .insert({
      proposal_id: payload.proposalId,
      channel: payload.channel,
      direction: payload.direction,
      interaction_at: payload.interactionAt,
      summary,
      details: payload.details?.trim() || null,
      recorded_by: uid,
      auto_generated: payload.autoGenerated ?? false,
      metadata: payload.metadata ?? {},
      created_by: uid,
      updated_by: uid,
    })
    .select("*")
    .single();
  if (error) throw error;
  return data as unknown as ProposalInteraction;
}

function invalidateProposalInteractions(qc: ReturnType<typeof useQueryClient>, proposalId: string) {
  qc.invalidateQueries({ queryKey: ["proposal_interactions", proposalId] });
  qc.invalidateQueries({ queryKey: ["proposal_interactions_count", proposalId] });
}

export function useCreateProposalInteraction() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: insertInteraction,
    onSuccess: (_data, vars) => invalidateProposalInteractions(qc, vars.proposalId),
    onError: (e: any) => toast.error(e?.message || "Erro ao registrar interação"),
  });
}

/**
 * Atalho silencioso: dispara um insert sem toast.
 * Usado pela action bar (clique WhatsApp) e por edge functions futuras.
 */
export function useRecordAutoInteraction() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (payload: CreateInteractionPayload) =>
      insertInteraction({ ...payload, autoGenerated: true }),
    onSuccess: (_data, vars) => invalidateProposalInteractions(qc, vars.proposalId),
    // Auto-registro é "fire and forget" — falha silenciosa para não bloquear o usuário.
    onError: (e: any) => {
      // Apenas log — não interrompe a ação principal (ex: abrir WhatsApp).
      // eslint-disable-next-line no-console
      console.warn("[useRecordAutoInteraction] falhou:", e?.message);
    },
  });
}

export function useUpdateProposalInteraction() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async (params: {
      id: string;
      proposalId: string;
      patch: Partial<Pick<ProposalInteraction, "channel" | "direction" | "interaction_at" | "summary" | "details">>;
    }) => {
      const userRes = await supabase.auth.getUser();
      const uid = userRes.data.user?.id ?? null;
      const { error } = await supabase
        .from("proposal_interactions" as any)
        .update({ ...params.patch, updated_by: uid })
        .eq("id", params.id);
      if (error) throw error;
    },
    onSuccess: (_d, vars) => invalidateProposalInteractions(qc, vars.proposalId),
    onError: (e: any) => toast.error(e?.message || "Erro ao atualizar interação"),
  });
}

export function useDeleteProposalInteraction() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async (params: { id: string; proposalId: string }) => {
      const userRes = await supabase.auth.getUser();
      const uid = userRes.data.user?.id ?? null;
      const { error } = await supabase
        .from("proposal_interactions" as any)
        .update({ deleted_at: new Date().toISOString(), updated_by: uid })
        .eq("id", params.id);
      if (error) throw error;
    },
    onSuccess: (_d, vars) => invalidateProposalInteractions(qc, vars.proposalId),
    onError: (e: any) => toast.error(e?.message || "Erro ao remover interação"),
  });
}

/**
 * Conta interações ativas (para badge na aba Interações).
 * Query separada e leve, sem trazer dados.
 */
export function useProposalInteractionsCount(proposalId: string | undefined) {
  return useQuery({
    queryKey: ["proposal_interactions_count", proposalId],
    enabled: !!proposalId,
    queryFn: async (): Promise<number> => {
      const { count, error } = await supabase
        .from("proposal_interactions" as any)
        .select("id", { head: true, count: "exact" })
        .eq("proposal_id", proposalId!)
        .is("deleted_at", null);
      if (error) throw error;
      return count ?? 0;
    },
  });
}
